# Prometheus配置文件

# 全局配置
global:
  scrape_interval:      15s         # 数据拉取间隔时间，default = 1 min
  scrape_timeout:       10s         # 单次数据拉取超时时间，default = 10 s
  evaluation_interval:  15s         # 规则拉取间隔时间，defalut = 1 min
  # external_labels:                  # 该prometheus服务和其他系统对接时的标签
  #   monitor: 'Arch-Linux'             # key: value

# 告警管理器配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# 规则文件配置
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 监控端点配置
scrape_configs:
  ## 监控prometheus本身
  - job_name: 'prometheus'          # job名称，是一个拉取单元，将作为标签"job = <job_name>"添加到此端点获取到的时间序列数据中
    # honor_labels: false             # 标签准则，false以配置文件为准，true以数据为准
    metrics_path: '/metrics'        # 指标路径，prometheus在这个路径抓取数据，default = '/metrics'
    scheme: 'http'                  # 抓取数据使用的协议，default = 'http'
    static_configs:                 # 静态配置抓取目标
      - targets: ['localhost:9090'] # 抓取目标
  ## 使用node-exporter监控主机
  - job_name: 'node'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['node-exporter:9100']
