# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-15 09:40:43

# Description: Watches your containers and automatically restarts them whenever their image is refreshed

version: '3.7'
services:
  watchtower:
    image: 'v2tec/watchtower'
    container_name: 'watchtower'
    restart: 'unless-stopped'       # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      watchtower: {}
    environment:
      TZ: 'Asia/Shanghai'
      WATCHTOWER_POLL_INTERVAL: '43200'      # 间隔0.5天
      WATCHTOWER_CLEANUP: 'true'
    labels:
      servicename: 'watchtower'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


networks:
  watchtower:
    name: 'watchtower'
